// R-85: deployment-level backup routes (NOT company-scoped — the whole
// Postgres is the backup unit). Every route is gated by requireAdmin:
// company membership (R-03) does not confer deployment admin; non-admins
// get the same neutral 404 the company gate returns.
//
// The OAuth callback is a browser navigation (cookie-authenticated like
// every other route): Google redirects the operator's browser back with
// ?code&state. The state nonce (CSRF) is generated by /oauth/start, held
// in-memory for 10 minutes together with the exact redirect URI used (Google
// validates the exchange's redirect_uri against the authorize's), and the
// UI path to return to.

import { FastifyInstance } from "fastify";
import crypto from "node:crypto";
import { z } from "zod";
import { requireAdmin, bad } from "../lib/routes.js";
import { authorizeUrl, exchangeCode, revokeToken } from "../lib/gdrive.js";
import * as backups from "../services/backups.js";
import * as companyBackups from "../services/companyBackups.js";
import { db } from "../db/index.js";
import { companies } from "../db/schema.js";
import { eq, asc } from "drizzle-orm";

const stateStore = new Map<string, { redirectUri: string; returnTo: string; exp: number }>();
const STATE_TTL = 10 * 60_000;

function redirectUriFor(req: any): string {
  const proto = String(req.headers["x-forwarded-proto"] ?? req.protocol ?? "http").split(",")[0].trim();
  const host = String(req.headers.host ?? `localhost:${process.env.PORT ?? "3000"}`);
  return `${proto}://${host}/api/backups/oauth/callback`;
}

// .strict(): unknown fields (e.g. anything smelling like a destination URL)
// are rejected outright — the API surface must have no destination knob at all.
const settingsPatchSchema = z.strictObject({
  clientId: z.string().trim().max(300).optional(),
  clientSecret: z.string().max(300).optional(), // omitted = unchanged (R-28)
  folderName: z.string().trim().max(100).optional(),
  scheduleKind: z.enum(["off", "daily", "weekly"]).optional(),
  scheduleDow: z.number().int().min(0).max(6).nullable().optional(),
  scheduleHhmm: z.string().regex(/^\d{2}:\d{2}$/, "Invalid time").optional(),
  retentionCount: z.number().int().min(1).max(365).optional(),
  enabled: z.boolean().optional(),
});

// Base shape: zprime-<date>T<time> with the optional uniqueness tail added by
// the engine (rapid runs must never share one name). R-88: company-scoped
// dumps carry a `-<cid>-<company-slug>-` infix (runCompanyBackup) — the
// restore route must accept the exact names its own backup path produces;
// restoreCompany re-verifies the manifest scope (cid) before applying.
const restoreSchema = z.object({
  base: z.string().regex(
    /^(?:zprime-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}(-[a-f0-9]{4})?|zprime-\d+-[a-zA-Z0-9_-]{1,60}-\d{4}-\d{2}-\d{2}T\d{2}-\d{2}-\d{2}-[a-f0-9]{4})$/,
    "Invalid backup name"),
  // R-88: optional scope — default (omitted) = deployment (current behavior);
  // { scope: "company", companyId } = per-company restore (in-place, scoped to
  // one cid). companyId must be a real company in the instance.
  scope: z.lazy(() =>
    z.union([
      z.object({ scope: z.literal("company"), companyId: z.number().int().min(1) }),
      z.object({ scope: z.literal("deployment") }).optional(),
    ]),
  ).optional(),
});

// R-88: the backup run body may name a scope (deployment = default/current,
// company = per-company manual backup). Zod strict keeps the surface closed.
const runSchema = z.object({
  // R-88: per-company manual backup — omitted = deployment (current behavior).
  scope: z.union([
    z.object({ scope: z.literal("company"), companyId: z.number().int().min(1) }),
    z.object({ scope: z.literal("deployment") }).optional(),
  ]).optional(),
});

/** R-85: rethrow an operational backup failure so the sanitizer passes OUR
 *  operator-facing wording (never SQL/stacks — these messages are authored
 *  server-side) to the UI on a non-4xx status. */
function opError(err: any, fallback: string): Error {
  const msg = String(err?.message ?? err) || fallback;
  return Object.assign(new Error(msg), { statusCode: 500, expose: true });
}

export default async function backupRoutes(app: FastifyInstance) {
  const admin = async (req: any) => requireAdmin(req);

  app.get("/backups/settings", async (req) => {
    await admin(req);
    return backups.getSettings();
  });

  app.put("/backups/settings", async (req) => {
    const uid = await admin(req);
    const parsed = settingsPatchSchema.safeParse(req.body);
    if (!parsed.success) throw bad(`Invalid settings: ${parsed.error.issues[0]?.message}`);
    await backups.updateSettings(parsed.data);
    return { ok: true, ...(await backups.getSettings()) };
  });

  app.post("/backups/oauth/start", async (req) => {
    await admin(req);
    const body = (req.body ?? {}) as any;
    const settings = await backups.getSettings();
    if (!settings.clientId || !settings.hasClientSecret) {
      throw bad("Save the Google Cloud client ID and secret first");
    }
    const state = crypto.randomBytes(16).toString("hex");
    const redirectUri = redirectUriFor(req);
    const returnTo =
      typeof body?.returnTo === "string" && (body.returnTo.startsWith("/company/") || body.returnTo === "/backups")
        ? body.returnTo
        : "/companies";
    stateStore.set(state, { redirectUri, returnTo, exp: Date.now() + STATE_TTL });
    for (const [k, v] of stateStore) if (v.exp < Date.now()) stateStore.delete(k);
    return { url: authorizeUrl({ clientId: settings.clientId }, redirectUri, state) };
  });

  // Browser navigation from Google's consent screen — the session cookie
  // authenticates (same as every other route); the state nonce defeats CSRF.
  app.get("/backups/oauth/callback", async (req, reply) => {
    await admin(req);
    const q = (req.query ?? {}) as any;
    const state = String(q.state ?? "");
    const entry = stateStore.get(state);
    if (!entry || entry.exp < Date.now()) {
      return reply.code(400).send({ error: "OAuth state expired or unknown — start the connection again" });
    }
    stateStore.delete(state);
    if (q.error) {
      await backups.recordLifecycle("connect", req.userId ?? 0, `Google returned: ${q.error}`).catch(() => undefined);
      return reply.redirect(`${entry.returnTo}?backups=${encodeURIComponent(`Google returned: ${q.error}`)}`);
    }
    const settings = await backups.getSettings();
    const code = String(q.code ?? "");
    let clientCreds: { clientId: string; clientSecret: string };
    try {
      clientCreds = await backups.oauthCreds();
    } catch (err: any) {
      return reply.redirect(`${entry.returnTo}?backups=${encodeURIComponent(String(err?.message ?? err).slice(0, 200))}`);
    }
    if (!code) {
      return reply.redirect(`${entry.returnTo}?backups=${encodeURIComponent("Missing authorization code")}`);
    }
    try {
      const { refreshToken } = await exchangeCode(clientCreds, entry.redirectUri, code);
      await backups.storeRefreshToken(refreshToken);
      await backups.recordLifecycle("connect", req.userId ?? 0).catch(() => undefined);
      return reply.redirect(`${entry.returnTo}?backups=connected`);
    } catch (err: any) {
      await backups.recordLifecycle("connect", req.userId ?? 0, String(err?.message ?? err)).catch(() => undefined);
      return reply.redirect(`${entry.returnTo}?backups=${encodeURIComponent(String(err?.message ?? err).slice(0, 200))}`);
    }
  });

  app.post("/backups/disconnect", async (req) => {
    await admin(req);
    await backups.disconnect();
    await backups.recordLifecycle("disconnect", req.userId ?? 0).catch(() => undefined);
    return { ok: true };
  });

  // R-88: a lightweight admin-only company list for the per-company picker
  // (deployment scope — every company in the instance). The normal
  // /api/companies endpoint is membership-gated (a deployment admin may not hold
  // membership to every company), so the picker needs its own admin view.
  app.get("/backups/companies", async (req) => {
    await admin(req);
    return db.select({ id: companies.id, name: companies.name }).from(companies).orderBy(asc(companies.name));
  });

  app.get("/backups/runs", async (req) => {
    await admin(req);
    return backups.history();
  });

  app.post("/backups/run", async (req) => {
    const uid = await admin(req);
    const parsed = runSchema.safeParse((req.body ?? {}) as any);
    if (!parsed.success) throw bad(`Invalid run request: ${parsed.error.issues[0]?.message}`);
    const scope = parsed.data.scope;
    if (scope?.scope === "company") {
      // R-88: per-company manual backup — the company must exist in the instance.
      const [company] = await db.select().from(companies).where(eq(companies.id, scope.companyId)).limit(1);
      if (!company) throw bad(`Company ${scope.companyId} not found`, 404);
      try {
        const out = await companyBackups.runCompanyBackup({ cid: company.id, companyName: company.name }, "manual", uid);
        return { ok: true, ...out };
      } catch (err: any) {
        if (String(err?.message ?? "").includes("already running")) throw bad("A backup or restore is already running", 409);
        throw opError(err, "Backup failed");
      }
    }
    // default = deployment (current behavior, unchanged)
    try {
      const out = await backups.runBackup("manual", uid);
      return { ok: true, ...out };
    } catch (err: any) {
      if (String(err?.message ?? "").includes("already running")) throw bad("A backup or restore is already running", 409);
      throw opError(err, "Backup failed");
    }
  });

  app.get("/backups/remote", async (req) => {
    await admin(req);
    // R-88: the remote list now carries scope so the UI can render/filter by it.
    return backups.listRemoteScoped();
  });

  // The destructive path: typed confirmation is enforced client-side AND the
  // route requires the literal word in the body (double gate).
  app.post("/backups/restore", async (req) => {
    const uid = await admin(req);
    const parsed = restoreSchema.safeParse((req.body ?? {}) as any);
    if (!parsed.success) throw bad(`Invalid restore request: ${parsed.error.issues[0]?.message}`);
    const confirm = String((req.body as any)?.confirm ?? "");
    if (confirm !== "RESTORE") throw bad("Type RESTORE to confirm — restoring replaces the entire database", 400);
    const scope = parsed.data.scope;
    if (scope?.scope === "company") {
      // R-88: per-company in-place restore. companyId must be a real company.
      if (!scope.companyId) throw bad("companyId is required for a company restore", 400);
      const [company] = await db.select().from(companies).where(eq(companies.id, scope.companyId)).limit(1);
      if (!company) throw bad(`Company ${scope.companyId} not found`, 404);
      try {
        const out = await companyBackups.restoreCompany(parsed.data.base, company.id, uid);
        return { ok: true, ...out };
      } catch (err: any) {
        if (String(err?.message ?? "").includes("already running")) throw bad("A backup or restore is already running", 409);
        // A manifest-scope/cid mismatch is a caller mistake (the selected pair
        // belongs to a different company) — 400, not an operational failure.
        if (/scope mismatch/i.test(String(err?.message ?? ""))) throw bad(String(err?.message ?? err), 400);
        throw opError(err, "Restore failed");
      }
    }
    // default = deployment (current behavior, unchanged)
    try {
      const out = await backups.restoreBackup(parsed.data.base, uid);
      return { ok: true, ...out };
    } catch (err: any) {
      if (String(err?.message ?? "").includes("already running")) throw bad("A backup or restore is already running", 409);
      throw opError(err, "Restore failed");
    }
  });
}
